FROM grafana/otel-lgtm
COPY otelcol-config.yaml /otel-lgtm/otelcol-config.yaml
COPY grafana-dashboards.yaml /otel-lgtm/grafana/conf/provisioning/dashboards/haramblock.yaml
COPY dashboards/ /otel-lgtm/dashboards/haramblock/
